### PR TITLE
Change credit from "Moritz Brückner" to "Momel15"

### PR DESCRIPTION
**Pull request by MoritzBrueckner**
When I made the first pull request, I made a mistake configuring GitHub
so my full name was displayed. So I would like to change the name in the
credits back to my user name.

### CODE REVIEW

**Comment by MoritzBrueckner** [comment]
I made a mistake. As it seems Github automatically adds commits to a pull request when this is not merged at that point.
The commits `654226d`, `2a60de3`, `bd7e160` and `4996023` should not be a part of this pull request, I made them in my fork and wanted to sync them only with that.

How to avoid this?

**Comment by alabd14313** [comment]
Hello @Momel15 !
There is a button right hand side "Revert". revert it, then make a new branch and change it your favourites:
git checkout cdeb24b
 Finally create a new PR.

**Comment by alabd14313** [comment]
It is usually better to create a new branch from master, not from other branches.

**Comment by MoritzBrueckner** [comment]
I did this, but accidently I created another branch on this repo^^ I'm sorry. I better just do one thing at a time because I don't fully understand github^^

Would you delete the branch pr26 for me? I better don't do things like that to prevent myself from accidentally make things worse. Sorry about that again :(

**Comment by alabd14313** [comment]
@Momel15 don't worry. pr26 is your local and fork branch. It have not effect on upstream repos.

**Comment by MoritzBrueckner** [comment]
No it is not a local branch, you can see it on the main (code) page of this repo

Its because I was in the wrong directory when reverting the commits

**Review by mikepan — APPROVED** [review]

**Comment by mikepan** [comment]
Should be okay now. I only merged the credit change request.

**Comment by MoritzBrueckner** [comment]
Thank you :)

**Pull request merged**
